name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, bathroom]
    steps:
      - uses: actions/checkout@v3

      - name: Rust release build
        shell: bash
        run: |
          . "$HOME/.cargo/env"
          cargo build --release

      - name: Restart systemd service
        shell: bash
        run: |
          sudo systemctl restart wot-replay-api.service
